"use strict";

var _ = require("lodash");

var git = require("./git");


module.exports = {
  "list":   list,
  "unset":  unset,
  "set":    set,
  "get":    get,
  "prefix": prefix
};

module.exports.defaults = {
  "inject-issue":     false,
  "user":             null,
  "repo":             null,
  "context":          3,
  "case-sensitive":   false,
  "signature":        "(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))",
  "label-whitespace": true,
  "label.TODO":       "TODO",
  "label.FIXME":      "TODO"
};

var PREFIX = "github-todos";

module.exports.booleans = [
  "inject-issue",
  "case-sensitive",
  "label-whitespace"
];


// Get/Set options section
var PREFIX = "github-todos";
function prefix (value) {
  if (value) {
    PREFIX = value;
  }

  return PREFIX;
}

// Check if an option should have a boolean value
function isBoolean (key) {
  return _.contains(module.exports.booleans, key);
}

function asBoolean (value) {
  if (_.isBoolean(value)) {
    return value;
  }
  var iValue = parseInt(value);
  if (!isNaN(iValue)) {
    return value !== 0;
  }
  try {
    return !!JSON.parse(value);
  } catch (e) {
    return false;
  }
}

function list (cb) {
  git.run("config --local --get-regexp " + PREFIX + ".*", function (err, stdout) {
    if (err) {
      return cb(err);
    }

    var result = {};
    stdout.trim().split("\n").forEach(function (line) {
      var key = line.substring(PREFIX.length + 1, line.indexOf(" "));
      var value = line.substring(PREFIX.length + 1 + key.length + 1).trim();
      result[key] = isBoolean(key) ? asBoolean(value) : value;
    });

    cb(null, result);
  });
}

function unset (option, cb) {
  git.run("config --local --unset " + PREFIX + "." + option, function (err /*, stdout */) {
    if (err.code === 5) {
      // config option already didn't exist, just ignore this case
      err = null;
    }
    cb(err || null);
  });
}

function get (option, cb) {
  // `git config option` returns 1 if option is not set
  // it also returns 1 if we're out of a git repository :(
  // re-use exports.list to distinguish cases
  list(function (err, list) {
    if (err) {
      return cb(err);
    }

    cb(null, list[option] || null);
  });
}

function set (option, value, cb) {
  git.run("config --local " + PREFIX + "." + option + " " + value, function (err /*, stdout */) {
    cb(err || null);
  });
}
